service: apollo-server-ts

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 120

functions:
  graphql:
    handler: dist/src/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
      - http:
          path: graphql
          method: get
          # cors: true

plugins:
  - serverless-offline
